### ISSUE TITLE
Installing fails with R 3.0.2

### ISSUE THREAD

**Issue by robertzk** [yihui/knitr#1010]
This is specified as the minimum version of R, but `tools::vignetteEngine` does not have an `aspell` argument in this version of R, and thus we run into:

```
 call: tools::vignetteEngine(..., tangle = tangle, package = "knitr",
 error: unused argument (aspell = list(filter = knit_filter))
```

This is due to [this line](https://github.com/yihui/knitr/blob/master/R/utils-vignettes.R#L102).

**Comment by yihui** [comment]
Thanks! Should be fixed now.

**Comment by jdsjr** [comment]
I have tried installing knitr from the stable version on CRAN (several mirrors), XRAN and using devtools, all as described in the README.  And in all cases I am still getting "ERROR: this R is version 3.0.2, package 'knitr' requires R > 3.0.2".  Am I not picking up this fix or is something else going on?  Thanks in advance.

**Comment by yihui** [comment]
@jdsjr The error message has told everything: knitr requires R > 3.0.2, so R 3.0.2 is not sufficient. The only way is to upgrade your R (which is almost 3 years old now).
