### ISSUE TITLE
`include_graphics` output not suppressed by `fig.show='hide'`

### ISSUE THREAD

**Issue by vincentarelbundock** [yihui/knitr#1675]
The `bookdown` docs sold me on the value of `include_graphics`. There, it says:

> The syntax for controlling the image attributes is the same as when images are generated from R code, e.g., chunk options fig.cap, out.width, and fig.show still have the same meanings.

However, `fig.show='hide'` does not appear to suppress the figure output. See below for a reproducible example (I installed the latest CRAN version of `knitr` before running).

My use-case: I want images to appear in the PDF output but be substituted by "[Insert Figure Here]" in the Word output. To achieve this, I wrote a `knit_hook` which flips the `fig.show` switch and pastes in the necessary text. Unfortunately, this doesn't work for chunks where I call `include_graphics`, because `fig.show` won't suppress the image.

````
---
title: "suppress include_graphics output"
output: html_document
---

```{r, fig.show='hide'}
library(knitr)
knitr::include_graphics('https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Eastern_Grey_Squirrel.jpg/290px-Eastern_Grey_Squirrel.jpg')
```

```{r, fig.show='hide'}
x <- rnorm(10)
y <- rnorm(10)
plot(x, y)
```

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by vincentarelbundock** [comment]
wonderful! Thanks so much for your amazing work on this. I'm working on a book for a university press and `bookdown` is making writing this a joy (OK, maybe not a "joy", but you get my point.)

**Comment by davidlma** [comment]
How one could use the fix? I still see this using markdown  RStudio version 1.2.1335 and I updated knitr to latest.
